language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
 script:
  - nosetests --with-coverage modules/tests/test_create_room.py modules/tests/test_add_person.py
after_success: coveralls
cache: pip
